name: "Repocket"
slug: "repocket"
description: "Turn your unused internet into cash"
image: repocket/repocket
version: "1.2.0"
init: false
legacy: true
arch:
  - aarch64
  - amd64
options:
  RP_EMAIL: ""
  RP_API_KEY: ""
schema:
  RP_EMAIL: str
  RP_API_KEY: str
