name: "EarnApp"
slug: "earnapp"
description: "Earn passive income while your devices rest"
image: madereddy/earnapp
version: "1.607.304"
init: false
legacy: true
arch:
  - aarch64
  - amd64
  - armv7
options:
  EARNAPP_UUID: "sdk-node-XXXX"
schema:
  EARNAPP_UUID: str
