name: "EarnFM"
slug: "earnfm"
description: "Earn money online,passively."
version: "2026.09.10"
init: false
legacy: true
arch:
  - aarch64
  - amd64
  - armv7
options:
  EARNFM_TOKEN: ""
schema:
  EARNFM_TOKEN: str