name: "Traffmonetizer"
slug: "traffmonetizer"
description: "Share your internet connection and make money online"
version: "2026.10.03"
init: false
legacy: true
arch:
  - amd64
  - aarch64
options:
  token: ""
  device_name: "HomeAssistant"
schema:
  token: str
  device_name: str
